service: image-analysis

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  iam: 
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'rekognition:DetectLabels'
          Resource: "*"
        - Effect: 'Allow'
          Action:
            - 'translate:TranslateText'
          Resource: "*"
  lambdaHashingVersion: 20201221

functions:
  img-analysis:
    handler: handler.main
    events:
      - http:
          path: /
          method: get